### ISSUE TITLE
Repeated results by discover_ldap_domain_controllers_in_domain function

### ISSUE THREAD

**Issue by reach4bawer** [zorn96/ms_active_directory#1]
@zorn96 - I am using the following function to find all the domain controllers in the domain. When I executed the following function - 

`ldap_servers = discovery_utils.discover_ldap_domain_controllers_in_domain(domain=DOMAIN_URI, secure=True)`

returns same url repeated. The `secure=True or False` didn't make any changes.

I did some debugging and `discover_ldap_domain_controllers_in_domain` function in discovery_utils.py function  returns correct value till line `all_ldap_records = _resolve_record_in_dns(ldap_srv, SRV, dns_nameservers, source_ip)` but `_order_ldap_servers_by_rtt(all_ldap_records, server_limit, source_ip, secure)` returns repeated value. 

The following function is something that could be causeing the problem. 
```
def _order_ldap_servers_by_rtt(ldap_server_records: List[tuple], server_limit: int, source_ip: str, secure: bool):
    """ Take in a list of LDAP server records and determine the reachability and round trip time to each.
    Order them by RTT, fastest first, and drop unreachable servers. If there's more than our limit,
    trim the length based on our limit.
    """
    lookup_rtt_fns = []
    for server_tuple in ldap_server_records:
        # we don't care about weight and priority anymore if ordering by RTT
        server_host, server_port, _, _ = server_tuple
        fn = lambda: _check_ldap_server_availability_and_rtt(server_host, server_port, source_ip, secure)
        lookup_rtt_fns.append(fn)
    return _process_sort_return_rtt_ordering_results(lookup_rtt_fns, 'LDAP', server_limit)
```
specifically - `_process_sort_return_rtt_ordering_results`

I tested it on Amazon Linux and Macbook both return repeated results.

NSlookup from terminal gives different results.

**Comment by zorn96** [comment]
wow, my first bug! woohoo big milestone.

that's interesting though. `_process_sort_return_rtt_ordering_results` only evaluates once per rtt function passed in.
are the uris perfect duplicates?

there's an issue in windows 2016/2019 where you can end up with duplicate SRV records if a domain controller has uppercase letters in its name
https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/dns-registers-duplicate-srv-records-for-dc

I should actually probably enhance this to de-duplicate those records before we evaluate RTT, since they're equivalent.
it looks like nslookup might only return 1 record in these cases, as some users in other communities have seen nslookup only return the uppercase record even when both exist. ex: https://community.spiceworks.com/topic/2130914-duplicate-dc-records-in-dns
`nslookup` does a lot of hand-holding for users to make things more friendly (like intuiting out how to handle PTR records, ips, etc.) so this is unsurprising

I can definitely make the enhancement. I was planning to cut a 1.1.0 with some other enhancements later today.
but it would be helpful to know if there are duplicate records in your dns if that's something you can check :)

**Comment by reach4bawer** [comment]
Do you need me to just check if I get duplicate records when executing `nslookup -type=srv _kerberos._tcp.dc._msdcs.{domainname}`? If yes then sadly there are no duplicates and everything returned is lowercase.

**Comment by zorn96** [comment]
@reach4bawer I actually don't think `nslookup` will let you know, given that it seems to screen out the duplicates based on that second link I included.
`dig` might work, but I'm not certain. you might need actual access to the dns server

I've reproduced this in my test domain. here's an image of my dns with the same record just with different capitalizations
<img width="1057" alt="Screen Shot 2021-08-23 at 4 02 05 PM" src="https://user-images.githubusercontent.com/6414648/130532765-6330a749-ef55-41f6-a844-1d1b1bafb608.png">


yet nslookup produces only 1
```
azariazornberg@Azarias-MacBook-Pro ms_active_directory % nslookup -type=SRV _ldap._tcp.dc._msdcs.az.local
Server:		192.168.184.2
Address:	192.168.184.2#53

_ldap._tcp.dc._msdcs.az.local	service = 0 99 389 win-3cdvp8tigga.AZ.LOCAL.
```

I'll make sure to include an enhancement to resolve this in version 1.1.0 of the library later tonight.

**Comment by zorn96** [comment]
the word `_ldap` somehow vanished in my screenshot, but i promise the latter 2 records are both `_ldap` service records

**Comment by zorn96** [comment]
here's a better screenshot. i added a 3rd record too with variable capitalization.
<img width="1059" alt="Screen Shot 2021-08-23 at 4 40 57 PM" src="https://user-images.githubusercontent.com/6414648/130533291-ce7d15eb-4664-4e84-bdc5-78f3174f1bca.png">

and I confirmed that the library gets duplicates with this setup. so I should definitely add a "cast to lowercase and dedupe" to the dns record lookup

**Comment by zorn96** [comment]
hi @reach4bawer ! version 1.1.0 has been released and should resolve this issue
https://pypi.org/project/ms-active-directory/1.1.0/
at your earliest convenience, I recommend giving it a try :)

**Comment by reach4bawer** [comment]
When I test the newly implemented function I am getting the first sever repeated again (tested it multiple times, don't have any repeated servers in the environment checked with the team managing the servers). 

        `fn = lambda: _check_ldap_server_availability_and_rtt(server_host, server_port, source_ip, secure)`

is creating a function with the same arguments on my end. I replaced this function with -

`fn = partial(_check_ldap_server_availability_and_rtt, server_host, server_port, source_ip, secure)`

where partial was imported like -  `from functools import partial` This gives me unique results. 

I am not sure why lambda generated the same function call.

**Comment by zorn96** [comment]
oof. i just did some looking into it and apparently it's an issue that lambdas don't properly remember variables that they're assigned in a loop. I only have one domain controller locally, which is why I didn't notice it. using `partial` seems like the right fix.
let me release a 1.1.1 real quick

**Comment by zorn96** [comment]
ok, 1.1.1 is out now using partials https://pypi.org/project/ms-active-directory/1.1.1/
I should really get a second domain controller going. thanks for the help in root causing this issue! :)

**Comment by zorn96** [comment]
rip this demo script
```
Python 3.8.7 (default, Feb 26 2021, 17:39:13) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a = ['test1', 'test2']
>>> fns = []
>>> for i in a:
...     fn = lambda: print(i)
...     fns.append(fn)
... 
>>> fns[0]()
test2
>>> fns[1]()
test2
>>> from functools import partial
>>> fns = []
>>> for i in a:
...     fn = partial(print, i)
...     fns.append(fn)
... 
>>> fns[0]()
test1
>>> fns[1]()
test2
>>> 
```

**Comment by reach4bawer** [comment]
I tested something similar. What are you using to create these domain controllers for your environment? Are you using docker or VM to bring the environment running ?

**Comment by zorn96** [comment]
yeah, I'm using vmware on my mac to run the domain controller. I'm on a pretty old macbook though, so I don't really have enough RAM to run 2 instances and still do other things.

once the new 16" M1 macs come out, I'm planning to turn my current macbook into an environment host full time so I can run multiple domains and domain controllers to develop and test multi-domain trust relationship mechanics as well. but that won't be for a few months

**Comment by reach4bawer** [comment]
I am waiting on the M1X mac (fingers crossed) hopefully it comes out soon. I am trying to setup my environment let me know if you have any tips :)
