### ISSUE TITLE
v1.7.0 has broken my atomic_append_to_attribute_for_user usage

### ISSUE THREAD

**Issue by AshleyJackson** [zorn96/ms_active_directory#11]
In previous versions this function works flawlessly, however in the latest version my script just keels over.
I have provided snippets of my terrible code and tests below and I am hoping that it is something simple that I am overlooking.

```users = session.find_users_by_common_name(user_cn, ['mail','name','manager','physicalDeliveryOfficeName', 'mobile'])
for user in users:
	name = user.get('name')
	manager = user.get('manager')
	email = user.get('mail')
	department = user.get('physicalDeliveryOfficeName')
	mobile = user.get('mobile')
	manager_dn = session.find_user_by_name(manager, ['name'])
if (type(mobile)) != str:
	# other Sensitive non-relevant code.
	session.atomic_append_to_attribute_for_user(user_cn, 'mobile', mobile)

print(type(mobile))
print(mobile)

```

![image](https://user-images.githubusercontent.com/12793989/132277985-5659983d-9b42-498d-92e1-f7c38780d8e9.png)

The above is the AD Types for the mobile attribute as seen by ms_active_directory.

With the above code, the below error happens when the _session.atomic_append_to_attribute_for_user(user_cn, 'mobile', mobile)_ is uncommented

```
  File "/home/ashley/.local/lib/python3.8/site-packages/ms_active_directory/core/ad_session.py", line 2359, in atomic_append_to_attribute_for_user
    return self.atomic_append_to_attribute_for_object(user, attribute, value, controls,
  File "/home/ashley/.local/lib/python3.8/site-packages/ms_active_directory/core/ad_session.py", line 2168, in atomic_append_to_attribute_for_object
    return self._do_something_to_attribute_for_object(ad_object, attr_map, controls, raise_exception_on_failure,
  File "/home/ashley/.local/lib/python3.8/site-packages/ms_active_directory/core/ad_session.py", line 2143, in _do_something_to_attribute_for_object
    raise AttributeModificationException('Failed when {} for the object within the domain. LDAP result: {}'
ms_active_directory.exceptions.AttributeModificationException: Failed when appending a value for an attribute for the object within the domain. LDAP result: {'result': 21, 'description': 'invalidAttributeSyntax', 'dn': '', 'message': '00000057: LdapErr: DSID-0C090FEC, comment: Error in attribute conversion operation, data 0, v4563\x00', 'referrals': None, 'type': 'modifyResponse'}
```

Hopefully this is something stupid and it is staring at me, I've read through the release notes and I've noted that you've incorporated annotations, however I am unsure what the solution would be.

Thanks in advance @zorn96

**Comment by zorn96** [comment]
Hi @AshleyJackson ! Were you checking the response from your function call in 1.6.1?
maybe try rolling back and printing the result of your append call? (It’ll be true or false)

i fixed a bug in 1.7.0 where certain functions weren’t raising errors properly when they failed.
I stepped out right after the release, but can take a look once I’m home to see if anything else changed. But i don’t think i really changed anything in this area

**Comment by AshleyJackson** [comment]
Apologies @zorn96 but I was wrong.
This error is always happening in anything from 1.5.0 onwards.

But what is even weirder, is that it was working shortly after I requested this functionality.

The error being output from the print is the exact same as the original
```
ms_active_directory.exceptions.AttributeModificationException: Failed when appending a value for an attribute for the object within the domain. LDAP result: {'result': 19, 'description': 'constraintViolation', 'dn': '', 'message': '00000057: LdapErr: DSID-0C090FEC, comment: Error in attribute conversion operation, data 0, v4563\x00', 'referrals': None, 'type': 'modifyResponse'}
```

I am kinda feeling that you are correct about it being a server side issue, however I am unsure...
I will have a look at our AD Servers.

Cheers.

**Comment by zorn96** [comment]
No problem. It’s not necessarily a server bug - the response suggests that the value you’re providing for mobile doesn’t pass the validation that your server is performing.

this might have to do with the format of your input. assuming mobile is a phone number, it could be something like the server expecting a country code while you don’t provide one. Or the server could want the phone number to have dashes, but your script doesn’t.

I’d recommend looking at existing users with values for mobile and comparing them across the value you’re appending

**Comment by AshleyJackson** [comment]
I have since figured this out.

My script was attempting to push a value of '' into an attribute and it was causing it to bug out.

I've since rewritten it to pick up on this and it now works flawlessly.
The issue was not to do with ms_active_directory.

Thanks for your assistance on this @zorn96

**Comment by zorn96** [comment]
Thanks for the heads up! I’ll go ahead and close this
