### ISSUE TITLE
Unable to connect via different service port

### ISSUE THREAD

**Issue by reederda** [zorn96/ms_active_directory#17]
When creating a connection, the module appears to utilize the default port. In environments where a different port is needed, this should be able to change.

**Comment by zorn96** [comment]
hi @reederda ! this is already supported actually.

one thing I'll point out is that when you utilize auto-discovery functionality, the library will use whatever port your domain has registered in DNS as being its port for the LDAP protocol. so if your domain cannot serve LDAP traffic over the port it's registered, then that's a misconfiguration and will cause pain with other tools too, not just this library

but there are workarounds already available.
when you create a domain object, you can specify `Server` objects or URIs for ldap servers. and those can be used to indicate the port, the protocol, and other settings as granularly as you'd like.

here's some examples - you can specify the protocol (LDAP with StartTLS vs. LDAPS, which are different ways of doing TLS), the port, etc.
```
uri_which_will_use_default_ldaps_port = 'ldaps://10.212.42.1'
uri_which_will_use_custom_ldaps_port = 'ldaps://10.214.52.4:1636'
hostname_which_will_use_ldap_start_tls_default_port = 'ex-hostname.example.com'
hostname_which_will_use_ldap_start_tls_other_port = 'ex-hostname.example.com:1389'

ldap_uris = [uri_which_will_use_default_ldaps_port, uri_which_will_use_custom_ldaps_port, hostname_which_will_use_ldap_start_tls_default_port, hostname_which_will_use_ldap_start_tls_other_port]

ex_domain = ADDomain('example.com', ldap_servers_or_uris=ldap_uris)
```
if you specify ldap uris then auto-discovery of ldap servers in dns won't be done.

if you look at the `ldap3` library's `Server` objects, you can also use those if (for example) you want custom CA certificate configurations or TLS version minimums per server or something like that.

hope this helps!

**Comment by reederda** [comment]
This was incredibly helpful, thank you! I was not aware of this method.

**Comment by zorn96** [comment]
Yeah I’m in the process of figuring out how to generate documentation, as I’ve never done it for a library before 😅 

If you look at the dev branch that’s actually what I’m working on right now haha. I figured I can’t just keep adding examples to the readme forever
