### ISSUE TITLE
Additional attributes in Create_User issues?

### ISSUE THREAD

**Issue by AshleyJackson** [zorn96/ms_active_directory#42]
Hello.
There is a good chance I am doing something wrong, however I am using code similar to the below to create a user however it is failing.

```
domain = ADDomain(ADDomain)
session = domain.create_session_as_user(AuthUsername,AuthPassword)

attribute_map = {
    'description': 'test'
}

user = session.create_user(
        first_name=firstName,
        last_name=lastName,
        username=ADUserName,
        object_location=OULoc,
        user_password=RandomPassword,
        additional_user_attributes=attribute_map

)
print(user)
```

This is erroring out with:
```
  File "C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python310\lib\site-packages\ldap3\core\connection.py", line 1008, in add
    raise LDAPAttributeError(self.last_error)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type additional_user_attributes
```

I haven't seen much documentation around the create_user function and more specifically the additional attributes.
I'm clearly missing something however it illudes me.

Is this something simple?

Thanks in advance.

**Comment by zorn96** [comment]
ah sorry for any confusion. `additional_user_attributes` in the function header is keyword arguments (`** additional_user_attributes`) so you would do your call like
```
user = session.create_user(
        first_name=firstName,
        last_name=lastName,
        username=ADUserName,
        object_location=OULoc,
        user_password=RandomPassword,
        description ='test'
)
```

the idea is that you pass as many or few keyword args as you want and it assembles them into a dictionary, that way you don't need to worry about things like user input sanitization. so you could also do
```

user = session.create_user(
        first_name=firstName,
        last_name=lastName,
        username=ADUserName,
        object_location=OULoc,
        user_password=RandomPassword,
        description ='test',
        uidNumber=100,
        gidNumber=2000,
        employeeNumber=100,
)
```

**Comment by AshleyJackson** [comment]
Ahhh, that makes sense.

I'll give it a try when I can.

Cheers.

**Comment by AshleyJackson** [comment]
Yup worked. Closing.

Thanks @zorn96
