### ISSUE TITLE
Abiliity to create a User without first and Last name

### ISSUE THREAD

**Issue by FabiChan99** [zorn96/ms_active_directory#47]
Hey, i want to create users ** without first and Last name**, is this possible?

**Comment by zorn96** [comment]
hi @FabiChan99 ! sorry for the delay on this - yes! you can create a user without a first and last name, as long as you specify the `common_name` parameter when doing so you can pass null values for first and last name

I had the function ask for first and last name by default and then use them to construct the common name unless an alternate one was specified. but for the purposes of AD, you don't need them
