### ISSUE TITLE
MS domain for Linux (Question)

### ISSUE THREAD

**Issue by krishna3008** [zorn96/ms_active_directory#52]
Hi,

I know the ms_active_directory is for windows system
Is this will work in Linux also or any other way to replicate the same behaviour as this library

**Comment by zorn96** [comment]
hi @krishna3008 ! this library works on linux, though it might require certain debians depending on your domain's requirements.
for example, if you want to use kerberos communication to talk to your domain (similarly to many windows machines) and you're running on ubuntu, you'll need `libsasl2-modules-gssapi-mit`. but if you just want NTLM or basic auth, then you don't need that
