### ISSUE TITLE
Move user to new OU

### ISSUE THREAD

**Issue by GrantMcLravy** [zorn96/ms_active_directory#53]
What would be the recommended way to move a user's organizational unit?

I see the ldap3 package has the [MODIFY_DN](https://ldap3.readthedocs.io/en/latest/modifydn.html) function, but when trying to use that directly, I'm getting an "LDAPInvalidDNError : attribute type not present"

```
    new_ou_location = 'OU=User Terminations,OU=Corporate,DC=Company,DC=com'
    cn = ad_term_user.common_name
    logger.info("User's current distinguished name is %s",cn)
    old_dn = ad_term_user.distinguished_name
    logger.info("User's current distinguished name is %s",old_dn)
    new_dn = f"CN={cn},{new_ou_location}"
    logger.info("Moving user to %s.",new_dn)

    logger.debug(f"Sending command to ldap connection : session.ldap_connection.modify_dn({old_dn},{cn},new_superior={str(new_ou_location)})")
    session.ldap_connection.modify_dn(old_dn,cn,new_superior=str(new_ou_location))
```

I would love a built in `session.move_user_ou` command.

Thank you for your help.

**Comment by zorn96** [comment]
hi @GrantMcLravy ! I can look at building this (assuming you still need it). in the future you can also feel free to put out PRs

my only real standards for contribution are:
- good docstrings
- type annotations present
- follow the naming conventions of existing functions

**Comment by zorn96** [comment]
new functions will be out in the next release

- move_object_by_dn
- move_user
- move_computer
- move_group
- rename_object_by_dn
- rename_group

**Comment by zorn96** [comment]
newest version with this functionality is available on pypi now https://pypi.org/project/ms-active-directory/1.13.0/
