### ISSUE TITLE
If a SASL mechanism is specified as the authentication type, the authentication type should switch to SASL and we should pass the SASL mechanism through

### ISSUE THREAD

**Issue by reach4bawer** [zorn96/ms_active_directory#6]
I was trying to see if I could connect to the domain using specific authentication mechanism and SASL mechanisms. I tried passing -

`session = domain.create_session_as_user(username , password , 'SASL')`

I also tried -

```
from ldap3 import SASL
session = domain.create_session_as_user(username , password , SASL)
```
I get - `ldap3.core.exceptions.LDAPSASLMechanismNotSupportedError: requested SASL mechanism not supported`

Is this something that you are still building?

**Comment by zorn96** [comment]
hi @reach4bawer ! it works, but you need to specify a sasl_mechanism like this
```
>>> from ldap3 import SASL, KERBEROS
>>> session = domain.create_session_as_user('Administrator@AZ.LOCAL', authentication_mechanism=SASL, sasl_mechanism=KERBEROS)
>>>
```

that example uses `KERBEROS`, but you can also use `GSSAPI`, `EXTERNAL`, `DIGEST-MD5`, or `PLAIN` depending on what you're trying to do. `SASL` describes the back and forth negotiation, but not the actual mechanism in use

hope that helps!
I'm also planning to add support for doing something like
```
>>> from ldap3 import SASL, KERBEROS
>>> main_session1 = main_dom.create_session_as_user('Administrator@AZ.LOCAL', authentication_mechanism=KERBEROS)
```
and the library just figuring out that that's SASL, but I haven't done that yet

**Comment by reach4bawer** [comment]
Awesome. Thanks for the quick explanation and the example. Your documentation has been great, maybe this would be a great addition. Also, if one is trying to get all the user that are part of an AD group (recursively) then would this example work or is that a different function? 

`second_level_groups_res1 = session.find_groups_for_group(example_group_obj, desired_group_attrs)
`

**Comment by zorn96** [comment]
oh. huh.
I haven't added `get_members_of_group` or `get_members_of_groups` functions yet. I only have member->group, not group->member.
that's a good idea.

right now a way to do it would be
```
example_group_dn = 'CN=group1,OU=groups,DC=example,DC=com'
group_with_members = session.find_group_by_name(example_group_dn, attributes_to_lookup=['member'])
# if we're not certain the group exists, make sure to check if it's None first
group_member_dn_list = group_with_members.get('member')

users_in_group = []
groups_in_group = []
for member_dn in group_member_dn_list:
    user = session.find_user_by_name(member_dn)  # include any attributes you want to look up about the users here
    if user is not None:
        users_in_group.append(user)
        continue
    # if you don't care about nested groups, you can skip this next part
    group = session.find_group_by_name(member_dn)
    if group is not None:
        groups_in_group.append(group)
        continue

    # could be a cross-domain user/group since I haven't implemented multi-domain support yet. could also be a printer or some other weird object type
    print('Member dn {} is neither a user nor a group within the domain'.format(member_dn))
```

theoretically you could also do a lookup for memberOf
```
example_group_dn = 'CN=group1,OU=groups,DC=example,DC=com'
users = session.find_users_by_attribute('memberOf', example_group_dn)  # include any attributes you want to lookup
```
this is fewer queries to the AD domain, but it puts the processing work on the domain controller, and will likely be a much longer query (though if your application is CPU-strained as is, and you can push this query to another thread and wait on the results, you may prefer that).
this is because `memberOf` is a virtual attribute, as is only constructed when it's requested. so filtering on it is much much slower than looking up `member` for the group and then looking up users/groups directly by DN (since a lookup by DN is very fast)

hope one of those 2 options helps.
when I implement it, I may add a flag like `minimize_local_queries` to select whether you want to put the work on the server or the local system

**Comment by reach4bawer** [comment]
Yea good idea. Another thing to consider would be if we are trying to get user attributes for all the group members then taking the second approach might be a little taxing on the domain controllers as you would need to either query the DC multiple times or create a query to get all the members along with their attributes at once.

**Comment by zorn96** [comment]
In the most recent version of the package, I added auto-pagination. So requests that can return a lot of entities (like finding users with a certain attribute) will automatically switch to making paginated requests to the server, thereby reducing the load it has to handle at one and letting it clean up in between page requests.

So requesting a lot of attributes for a lot of users shouldn’t be too bad on the domain. You can also configure the page size if you want to fiddle with the balance of number of queries vs response size to optimize for your environment

**Comment by zorn96** [comment]
I’ll leave this open pending my adding support for getting members to the package

**Comment by zorn96** [comment]
i did this a while ago (1.8.1 i think?)
closing this
