### ISSUE TITLE
inquiry about attribute 

### ISSUE THREAD

**Issue by aabuhasna** [zorn96/ms_active_directory#60]
Hi,

Thanks for this module, I tried to use it but I am unable to get some useful attributes such as prevent from accountable relation, password expiration date, account expiration date, last login, password last set, GUID, description, and DNS root. is there a way to get them

**Comment by zorn96** [comment]
hi @aabuhasna - those fields all exist, and you can look them up by specifying the appropriate LDAP attributes in `attributes_to_lookup` when searching for users by name/dn/etc.

there's examples in the docs - let me know if that helps
