### ISSUE TITLE
Resolve hostname to IP address?

### ISSUE THREAD

**Issue by codenotworking** [zorn96/ms_active_directory#81]
Can `ms_active_directory` resolve hostname to IP address?

I know `socket.gethostbyname()` can be used, the problem with that is it has a weird internal timeout that can't be controlled, in case the hostname can't be resolved to an IP address.

```python
from ms_active_directory import ADDomain

domain = ADDomain("ad1.company.com")
session = domain.create_session_as_user("user@company.com", "password")
computer = session.find_computer_by_name("some_computer_name")

# hostname to resolve to an IP address???
print(computer.name)
```

**Comment by zorn96** [comment]
hi @codenotworking - the computer name isn't actually a hostname.
in many AD domains, the computer name might be equivalent to the short hostname, but you'll want to look up the dns hostname attribute to get the actual dns hostnames for an account https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/5c578b15-d619-408d-ba17-380714b89fd1

as far as resolution of that, you can use the python dns library to have tighter controls over lookups. it gets installed already as part of this library as a deoendency
