### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by rlees85** [zorn96/ms_active_directory#83]
Just wondered how possible it would be to get a release? Since:

https://github.com/zorn96/ms_active_directory/pull/74
https://github.com/zorn96/ms_active_directory/pull/75
https://github.com/zorn96/ms_active_directory/pull/78
https://github.com/zorn96/ms_active_directory/pull/80

**Comment by zorn96** [comment]
hi! I actually forgot that I didn't cut a new release. I will do so later tonight

**Comment by zorn96** [comment]
a new release has been created in github and is available here in pypi
https://pypi.org/project/ms-active-directory/1.14.0/
