### ISSUE TITLE
SyntaxError: expected  ':' for elif first_name in file core\ad_session.py

### ISSUE THREAD

**Issue by nkshirsaga** [zorn96/ms_active_directory#87]
Latest release [1.14.0](https://pypi.org/project/ms-active-directory/1.14.0/) has following issue 

Caused due to PR https://github.com/zorn96/ms_active_directory/pull/86/files#diff-7aa8e01e4a4d31cdbb4fbb76211af92d17059694103afbc112454ea45f56054eR397

```
11:35:13    File "C:\Python311\Lib\site-packages\ntlie\domain_control\ad.py", line 6, in <module>
11:35:13      from ms_active_directory import ADDomain, DomainConnectException
11:35:13    File "C:\Python311\Lib\site-packages\ms_active_directory\__init__.py", line 32, in <module>
11:35:13      from ms_active_directory.core.ad_domain import (
11:35:13    File "C:\Python311\Lib\site-packages\ms_active_directory\core\ad_domain.py", line 57, in <module>
11:35:13      from ms_active_directory.core.ad_session import ADSession
11:35:13    File "C:\Python311\Lib\site-packages\ms_active_directory\core\ad_session.py", line 397
11:35:13      elif first_name
11:35:13                     ^
11:35:13  SyntaxError: expected ':'
```

**Comment by rlees85** [comment]
Yeah theres a new more bugs too, honestly my fault for not checking the code before raising PRs (sadly not a Python dev with all the tools set up). I will raise a PR that I've tested locally that fixes it

**Comment by zorn96** [comment]
I’ve merged the fixes and will make a new release when I get home tonight

**Comment by zorn96** [comment]
1.14.1 has been released

**Comment by zorn96** [comment]
To ensure this does not happen again, I've added pylint requirements for all PRs which run across all supported python versions and all major OSs (windows, mac, linux)

**Comment by zorn96** [comment]
https://github.com/zorn96/ms_active_directory/pull/90
