### ISSUE TITLE
ADSession move_computer fails with LDAPInvalidDnError: attribute type not present

### ISSUE THREAD

**Issue by cipriandroc** [zorn96/ms_active_directory#94]
Trying to move a computer object using the ADSession move_computer method.

I'm supplying these 2 parameters:

computer
Either an ADComputer object or string distinguished name referencing the computer to be modified.

new_parent_dn
The new DN to move the object to.

I queried the computer 
`computer = session.find_computer_by_name(computer_name)`

I tried by passing my computer object , the distinguished_name property of the computer object or the plain DN string of the computer directly from AD.
Same with the OU. I queried the OU as below
`ou = session.find_object_by_distinguished_name(distinguished_name=target_ou)`
Tried passing the distinguished_name property or just the plain text string

Getting this error

```
ms_active_directory/core/ad_session.py:3907, in ADSession._move_or_rename_object_by_dn(self, ad_object, new_parent_dn, new_name, controls, raise_exception_on_failure, skip_validation)
   3904 # do the modification.
   3905 logger.debug('Attempting modification -> object with common name %s and dn %s to new name %s and parent dn %s',
   3906              object_name, object_dn, new_name, new_parent_dn)
-> 3907 res = self.ldap_connection.modify_dn(object_dn, object_name, new_superior=new_parent_dn, controls=controls)
   3908 success, result, response, _ = ldap_utils.process_ldap3_conn_return_value(self.ldap_connection, res,
   3909                                                                           paginated_response=False)
   3910 # raise an exception with LDAP details that might be useful to the caller (e.g. bad format of attribute,

172         raise LDAPInvalidDnError('attribute type not present')
    174     if attribute_type == '<GUID':  # patch for AD DirSync
    175         return True

LDAPInvalidDnError: attribute type not present
```

I did notice that my computer object is an ADUser object so I could see why I can't pass it as the computer object but using plain string tells me that's not the issue
```
computer = session.find_computer_by_name(computer_name)
type(computer)
ms_active_directory.core.ad_objects.ADUser
```

```
raise InvalidLdapParameterException('The computer specified must be an ADComputer object or a string '
   [4247](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ms_active_directory/core/ad_session.py:4247)                                         'computer name.')
```

**Comment by cipriandroc** [comment]
Oups, I had the module installed for a while and didn't use it. Figured I should try to upgrade.
```
      Successfully uninstalled ms_active_directory-1.13.0
Successfully installed ms_active_directory-1.14.1
```

It worked after I did the upgrade. Did notice still that the computer object is still of type ADUser

**Comment by zorn96** [comment]
@cipriandroc computers _are_ users in active directory. that's why `ADComputer` inherits from `ADUser`. it's a microsoft thing, not a library thing
